version: '3'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.web
    container_name: aura_web
    depends_on:
      - aura_mysql
      - notebook
    links:
      - aura_mysql
      - notebook
    ports:
      - 9000:9000
    volumes:
      - data-volume:/aura-data
  notebook:
    image: jupyter/all-spark-notebook:07292b8ebdd5
    ports:
      - 8888
    volumes:
      - data-volume:/aura-data
    command: start-notebook.sh --NotebookApp.base_url=/aura-data --NotebookApp.token='9e4f96c5239743a8dd5910216c6f02dad89a58932d63db7f' --no-browser
  aura_mysql:
    build:
      context: .
      dockerfile: Dockerfile.mysql
    container_name: aura_mysql
    ports:
      - '3306:3306'
    volumes:
      - data-volume:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: '1qaz@wsx'

volumes:
  data-volume:
